package com.interview.reminder.controller;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.interview.reminder.model.Doctor;
import com.interview.reminder.repository.DoctorRepository;

@RestController
@RequestMapping("/doctor") // This means URL's start with /doctor
public class DoctorController {
	@Autowired // This means to get the bean called doctorRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private DoctorRepository doctorRepository;

	@PostMapping("/create")
	public @ResponseBody Doctor addNewDoctor(@RequestBody Map<String, String> body) {
		// @ResponseBody means the returned doctor is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		Doctor doctor = new Doctor(body.get("username"), body.get("password"));
		doctorRepository.save(doctor);
		return doctor;
	}
	
	@GetMapping("")
	public @ResponseBody Authentication viewDashBoard() {
		Authentication auth = SecurityContextHolder.getContext().getAuthentication();
		return auth;
	}
}
