package com.interview.reminder.controller;

import java.util.List;
import java.util.UUID;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.interview.reminder.model.Doctor;
import com.interview.reminder.model.Pair;
import com.interview.reminder.model.Patient;
import com.interview.reminder.repository.PairRepository;

@RestController
public class PairController {
	@Autowired // This means to get the bean called doctorRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private PairRepository pairRepository;

	@PostMapping("/pair/create")
	public @ResponseBody Pair addNewPair(@RequestBody Doctor doctor, @RequestBody Patient patient) {
		// @ResponseBody means the returned UUID is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		Pair pair = new Pair(doctor, patient);
		pairRepository.save(pair);
		return pair;
	}

	@GetMapping("/doctor/{doctor_id}/remind_list")
	public @ResponseBody List<Pair> getPatients(@PathVariable UUID doctor_id) {
		return pairRepository.findPatients(doctor_id);
	}

}
