package com.interview.reminder.controller;

import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.interview.reminder.model.Patient;
import com.interview.reminder.repository.PatientRepository;

@RestController
@RequestMapping("/patient") // This means URL's start with /patient
public class PatientController {
	@Autowired // This means to get the bean called patientRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private PatientRepository patientRepository;

	@PostMapping("/create")
	public @ResponseBody Patient addNewPatient(@RequestBody Map<String, String> body) {
		// @ResponseBody means the returned patient is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		Patient patient = new Patient(body.get("username"), body.get("password"));
		patientRepository.save(patient);
		return patient;
	}
}
