package com.interview.reminder.controller;

import java.util.List;
import java.util.UUID;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.interview.reminder.model.Reminder;
import com.interview.reminder.repository.ReminderRepository;

@RestController
public class ReminderController {

	@Autowired // This means to get the bean called doctorRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ReminderRepository reminderRepository;

	@GetMapping("/{doctor_id}/{patient_id}/history_reminder")
	public @ResponseBody List<Reminder> getHistoryReminders(@PathVariable UUID doctor_id,@PathVariable UUID patient_id){
		return reminderRepository.findHistoryReminders(doctor_id,patient_id);
	}

	@PostMapping("/{doctor_id}/{patient_id}/post_reminder")
	public @ResponseBody Reminder newReminder(@PathVariable UUID doctor_id,@PathVariable UUID patient_id,@RequestBody Reminder body){
		
		return null;
	}
}
